package hexlet.code;

import javax.sql.DataSource;
import java.sql.SQLException;

public class DatabaseInitializer {
    public static void initialize(DataSource dataSource) {
        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement()) {
            stmt.execute(
                    "CREATE TABLE IF NOT EXISTS page_analyzer ("
                            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                            + "name VARCHAR(255) NOT NULL, "
                            + "created_at TIMESTAMP NOT NULL);"
                            + "CREATE TABLE IF NOT EXISTS url_checks ("
                            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                            + "url_id BIGINT REFERENCES page_analyzer(id) ON DELETE CASCADE, "
                            + "status_code INTEGER, "
                            + "title VARCHAR(255), "
                            + "h1 VARCHAR(255), "
                            + "description TEXT, "
                            + "created_at TIMESTAMP);"
            );
            System.out.println("Database initialized successfully");
        } catch (SQLException e) {
            throw new RuntimeException("Failed to initialize database", e);
        }
    }
}

